name: Build & Release

on:
  push:
#    branches: [ master ]
    tags:    [ 'v*.*.*' ]
#  pull_request:
#    branches: [ master ]

permissions:
  contents: write   # allow creating/updating Releases & uploading assets
  actions:  read    # allow pulling marketplace actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter --version
#      - run: flutter build apk --release --split-per-abi
#      - run: flutter build appbundle

      - name: Build AAB
        run: flutter build appbundle --release

      - name: 📦 Prepare artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/bundle/release/*.aab artifacts/

      - name: 🏷️ Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.20.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: artifacts/*.aab
          token:     ${{ secrets.GITHUB_TOKEN }}

#  build_ios:
#    runs-on: macos-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#      - run: flutter pub get
#      - run: flutter --version
#      - run: flutter build ios --release --no-codesign
#
#      - name: 📦 Prepare artifacts
#        run: |
#          mkdir -p artifacts
#          cp -R build/ios/iphoneos/*.app artifacts/
#
#      - name: 🏷️ Create or update Release
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: ncipollo/release-action@v1.20.0
#        with:
#          tag:       ${{ github.ref_name }}
#          name:      Release ${{ github.ref_name }}
#          artifacts: artifacts/*.app
#          token:     ${{ secrets.GITHUB_TOKEN }}
